# Generated by Django 4.2.3 on 2023-07-18 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Class",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("class_id", models.CharField(max_length=15, unique=True)),
                ("teacher", models.CharField(max_length=5)),
                ("students", models.ManyToManyField(to="student.student")),
            ],
        ),
    ]
